# Generated by Django 4.0.3 on 2022-03-03 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Video name')),
                ('describtion', models.TextField(blank=True, verbose_name='Describtion')),
                ('videofile', models.FileField(upload_to='', verbose_name='Video file')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Game', 'Games'), ('Film', 'Films'), ('Dota', 'Dota')], max_length=10, verbose_name='Video category')),
                ('restrctions', models.CharField(choices=[('NO', 'No restriction'), ('VIOLATION', 'Violation'), ('BAN', 'Ban'), ('SHADOW', 'Shadow ban')], default='NO', max_length=10, verbose_name='Restrictions')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'VIDEO',
                'verbose_name_plural': 'VIDEOS',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='Like(1), Dislike(-1)')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Like/Dislike',
                'verbose_name_plural': 'Likes/Dislikes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment text')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.video')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
